# RGB Underglow (LEDバックライト) の有効化
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_SPI=y

# LEDの省電力設定
# 一定時間操作がない場合にLEDを消灯する
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# ZMK ディープスリープの有効化 (30分無操作でスリープ状態に移行)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# ZMK Studio の有効化 (PCからGUIでキーマップ変更可能にする)
CONFIG_ZMK_STUDIO=y
